[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["MajorX234 <majorx234@googlemail.com>"]
edition = "2018"

[dependencies]
num = "0.4"
image = {version = "0.24"}

[[bin]]
name = "mandelbrot" 
path = "src/main.rs"
